### Numpy

In [1]:
import numpy as np
np.__version__

'2.2.6'

In [2]:
L = range(1000)
%timeit L2 = [i ** 2 for i in L]

280 μs ± 17.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [3]:
arr = np.arange(1000)
%timeit arr2 = arr ** 2

1.22 μs ± 144 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
ar1 = np.array([1, 2, 3, 4])
print(ar1)
print(type(ar1))
ar1.dtype

[1 2 3 4]
<class 'numpy.ndarray'>


dtype('int64')

In [5]:
ar2 = np.array([1.1, 2.2, 3.3])
print(ar2)
print(type(ar2))
ar2.dtype

[1.1 2.2 3.3]
<class 'numpy.ndarray'>


dtype('float64')

In [7]:
ar3 = np.array([1, 2., 3])
print(ar3)
print(type(ar3))
ar3.dtype

[1. 2. 3.]
<class 'numpy.ndarray'>


dtype('float64')

In [11]:
ar4 = np.array([1, 2.2, 3.9], dtype=int)
print(ar4)
print(type(ar4))
ar4.dtype

[1 2 3]
<class 'numpy.ndarray'>


dtype('int64')

In [12]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [18]:
arr2 = arr1.reshape(-1, 3)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [ ]:
alist = [[0, 1, 2], [3, 4, 5]]

# [0, 1]
# [4, 5]
# [1 4]

print(alist[0][:2])
print(alist[1][1:3])
print(f"[{alist[0][1]} {alist[1][1]}]")

[0, 1]
[4, 5]
[1 4]


In [31]:
blist = np.array([[0, 1, 2], [3, 4, 5]])

# [0, 1]
# [4, 5]
# [1 4]

print(blist[0, :2])
print(blist[-1, 1:])
print(blist[:, 1])

[0 1]
[4 5]
[1 4]


In [36]:
clist = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

print(clist)
print(clist[[0, 2]])
print(clist[[0, 1, 2], [1, 2, 0]])
print(clist[:, 0], clist[:, 3])
print(clist[:, [0, 3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[1 6 8]
[0 4 8] [ 3  7 11]
[[ 0  3]
 [ 4  7]
 [ 8 11]]


In [ ]:
data = np.array([1, 4, 9, 16])

print(np.sqrt(data))
print(np.exp(data))
print(np.sum(data))
print(np.mean(data))
print(np.std(data))
print(np.var(data))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
30
7.5
5.678908345800274
32.25


: 

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 3의 배수 찾기

# 4로 나누면 1이 남는 수 찾기

# 3으로 나누어 떨어지고 4로 나누면 1이 남는 수 찾기

### Pandas

In [1]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [57]:
df = pd.read_csv("heroes.csv")
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [58]:
pd.options.display.float_format = '{:.0f}'.format

In [59]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 464.0+ bytes


In [10]:
df.describe()

나이   키             재산
count   7   7              5
mean   34 190  2300278000120
std    13  36  5142800956894
min    18 170            600
25%    26 172       50000000
50%    32 177      340000000
75%    39 184     1000000000
max    58 270 11500000000000

In [11]:
df.head(2)

이름  나이   직업     국적    키             재산
0  아이언맨  58  CEO     미국  174 11500000000000
1    토르  45    신  아스가르드  190            NaN

In [12]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [13]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [26]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [27]:
df[df['나이'] > 30]

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [31]:
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [24]:
df[3:5]

이름  나이     직업     국적    키         재산
3  원더우먼  27     공주  데미스키라  178        NaN
4    헐크  33  핵물리학자     미국  270 1000000000

In [18]:
df.iloc[[1, 3, 6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [ ]:
# df.iloc[행 번호, 열 번호]
df.iloc[:5, :3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [25]:
df.loc[3:5]

이름  나이     직업     국적    키         재산
3  원더우먼  27     공주  데미스키라  178        NaN
4    헐크  33  핵물리학자     미국  270 1000000000
5  캡틴마블  25    파일럿     미국  170  340000000

In [ ]:
# 키가 180 이상인 데이터에 대한 이름, 나이, 키 column만 출력
df.loc[df['키'] >= 180, ['이름', '나이', '키']]

이름  나이    키
1  토르  45  190
4  헐크  33  270

In [35]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [41]:
df['전투력'] = 98
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   98
1     토르  45      신  아스가르드  190            NaN   98
2  스파이더맨  18   고등학생     미국  177            600   98
3   원더우먼  27     공주  데미스키라  178            NaN   98
4     헐크  33  핵물리학자     미국  270     1000000000   98
5   캡틴마블  25    파일럿     미국  170      340000000   98
6  블랙위도우  32    스파이    러시아  170       50000000   98

In [42]:
df['전투력'] = df['전투력'] - 5
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  25    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [43]:
df.drop(columns=['전투력'], inplace=True)
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [45]:
df.dropna()

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [47]:
df['재산'].fillna(df['재산'].mean())

0   11500000000000
1    2300278000120
2              600
3    2300278000120
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [ ]:
df['재산'].fillna(method='ffill')   # ffill(front-fill) ↔ bfill(back-fill)

C:\Users\EL27\AppData\Local\Temp\ipykernel_14660\2183705569.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['재산'].fillna(method='ffill')


0   11500000000000
1   11500000000000
2              600
3              600
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [63]:
df2 = df
df2['키'] = df['키'].apply(lambda height: str(height) + 'cm')
df2

이름  나이     직업     국적      키             재산
0   아이언맨  58    CEO     미국  174cm 11500000000000
1     토르  45      신  아스가르드  190cm            NaN
2  스파이더맨  18   고등학생     미국  177cm            600
3   원더우먼  27     공주  데미스키라  178cm            NaN
4     헐크  33  핵물리학자     미국  270cm     1000000000
5   캡틴마블  25    파일럿     미국  170cm      340000000
6  블랙위도우  32    스파이    러시아  170cm       50000000